describe('Bookings page flow', () => {
    it('Check Edit "Last Name" - Order by - Delete', () => {
        cy.visit('/')
        cy.get('[for="password"] > input').type('{enter}')
        cy.contains('Bookings').click()
        cy.get(':nth-child(1) > .sc-blmEgr > :nth-child(1)').click()
        cy.get('[for="last_name"] > input').clear().type('AAAA')
        cy.get('.sc-iBdnpw').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'bookings')
        cy.get('.sc-khjJXk').select('Check In ↓')
        cy.get('.sc-fHejqy > :nth-child(1) > :nth-child(1) > div > :nth-child(1)').contains('Timmy Hannis')
        cy.get('.sc-khjJXk').select('Last Name ↓')
        cy.get('.sc-fHejqy > :nth-child(1) > :nth-child(1) > div > :nth-child(1)').contains('AAAA')
        cy.get(':nth-child(1) > .sc-blmEgr > :nth-child(1)').click()
        cy.get('[for="last_name"] > input').clear().type('BBBB')
        cy.get('.sc-iBdnpw').click()
        cy.get('.sc-khjJXk').select('Last Name ↓')
        cy.get('.sc-fHejqy > :nth-child(1) > :nth-child(1) > div > :nth-child(1)').contains('Berti Anstis')
        cy.get(':nth-child(1) > .sc-blmEgr > :nth-child(2)').click().wait(300)
        cy.get('.sc-fHejqy > :nth-child(1) > :nth-child(1) > div > :nth-child(1)').contains('Calli Arend')
    })
})