describe('New booking form', () => {
    it('Check Edit "Last Name" - Order by - Delete', () => {
        cy.visit('/')
        cy.get('[for="password"] > input').type('{enter}')
        cy.contains('Bookings').click()
        cy.contains('New Booking').click()
        cy.get('[for="first_name"] > input').type('Test Name')
        cy.get('[for="last_name"] > input').type('Test LastName')
        cy.get('[for="check_in"] > input').type('2024-01-01')
        cy.get('[for="check_out"] > input').type('2024-01-05')
        cy.get('textarea').type('Test Textarea')
        cy.get('[for="room_type"] > select').select('Double Bed')
        cy.get('[for="room_number"] > input').type('225')
        cy.get('[for="status"] > select').select('Check Out')
        cy.contains('Send').click()
        cy.contains('li', '5').click()
        cy.get('tr > :nth-child(1) > div > :nth-child(1)').contains('Test Name')
        cy.get('.request').click()
        cy.contains('Test Textarea')
        cy.get('body').click('top')
    })
})