
describe('Routing over Panel options', () => {
    it('from home to all over routes', () => {
        cy.visit('/')
        cy.get('[for="password"] > input').type('{enter}')
        cy.url().should('eq', Cypress.config().baseUrl)
        cy.contains('Bookings').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'bookings')
        cy.contains('Rooms').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'rooms')
        cy.contains('Contact').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'contact')
        cy.contains('Users').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'users')
    })
    it('reverse way', () => {
        cy.visit('/')
        cy.get('[for="password"] > input').type(`{enter}`)
        cy.url().should('eq', Cypress.config().baseUrl)
        cy.contains('Users').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'users')
        cy.contains('Contact').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'contact')
        cy.contains('Rooms').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'rooms')
        cy.contains('Bookings').click()
        cy.url().should('eq', Cypress.config().baseUrl + 'bookings')
	})
})
